version: '3'
services:
    
    angie_postgre:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./dbinit:/docker-entrypoint-initdb.d/
        ports:
            - 3132:5432/tcp
        
    angie_elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
        environment:
            - discovery.type=single-node
        ports:
            - 3103:3103
        volumes:
            - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./elastic/data:/usr/share/elasticsearch/data

    angie_kibana:
        image: docker.elastic.co/kibana/kibana:7.14.1
        ports:
            - 3108:5601
        volumes:
            - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        
        links:
            - "angie_elasticsearch:angie_elasticsearch"

    angie_rabbitmq: 
        image: rabbitmq:management
        ports: 
            - 3111:5672
            - 3112:15672