version: '3'
services:

    angie_postgre:
        image: postgres:13
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./dbinit:/docker-entrypoint-initdb.d/
        ports:
            - 3132:5432/tcp

    angie_elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 3103:3103
        volumes:
            - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./elastic/data:/usr/share/elasticsearch/data

    angie_kibana:
        image: docker.elastic.co/kibana/kibana:7.16.3
        ports:
            - 3108:5601
        volumes:
            - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        
        depends_on:
            - angie_elasticsearch
        links:
            - "angie_elasticsearch:angie_elasticsearch"

    angie_rabbitmq: 
        image: rabbitmq:management
        ports: 
            - 3111:5672
            - 3112:15672


    angie_keycloak:
        image: quay.io/keycloak/keycloak:latest
        ports:
            - 3114:8080
        volumes:
            - ./keycloak/themes/angie:/opt/jboss/keycloak/themes/angie
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: angie_postgre
            DB_DATABASE: keycloak
            DB_USER: postgres
            DB_SCHEMA: public
            DB_PASSWORD: root
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.upload_scripts=enabled"
        depends_on:
            - angie_postgre
    
    prometheus:
      container_name: prometheus
      image: prom/prometheus
      ports:
        - 3190:9090
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention=30d'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      volumes:
        - ./prometheus/:/etc/prometheus/
        - ./prometheus/prometheus_data:/prometheus
      # depends_on:
      #   - node_exporter

    grafana:
      container_name: grafana
      image: grafana/grafana
      ports:
        - 3100:3100
      volumes:
        - ./grafana/etc/grafana:/etc/grafana
        - ./grafana/var/lib/grafana:/var/lib/grafana
        - ./grafana/var/log/grafana:/var/log/grafana
      user: "1000"
      depends_on:
            - prometheus

    # node_exporter:
    #   image: quay.io/prometheus/node-exporter:latest
    #   container_name: node_exporter
    #   command:
    #     - '--path.rootfs=/host'
    #   network_mode: host
    #   pid: host
    #   restart: unless-stopped
    #   volumes:
    #     - '/:/host:ro'
